### ISSUE TITLE
Get Error Invalid Android message priority!

### ISSUE THREAD

**Issue by juniardys** [plokko/laravel-firebase#6]
When I send FCM notification, I get "Invalid Android message priority!" message?

**Comment by plokko** [comment]
Please before asking a generic question do provide a sample code and a detailed explaination, without this i cannot help you.
Also please do read Firebase official documentation before using this library as it's based on Firebase REST API

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/52727611/90293674-394dc180-deb7-11ea-9ef1-0c40085b144d.png)
![image](https://user-images.githubusercontent.com/52727611/90293688-3fdc3900-deb7-11ea-9967-4974d35293b7.png)

Hi, the plokko/laravel-firebase FcmMessageBuilder.php and the plokko/firebase-php AndroidConfig.php have conflict. That's why is cause the issue. After change AndroidConfig.php const value to lowercase, this issue will solve.
